### ISSUE TITLE
Subfilter

### ISSUE THREAD

**Issue by kasoft** [idiomReplaceX/idiomreplacex-service#4]
Aktuell gibt es sehr ähnliche Filter die nach dem selben Prinzip funktionieren. Zum Beispiel "a" durch "p" tauschen wäre ähnlich wie "r" durch "l" tauschen. Legt man jedes mal dafür einen neuen Filter an, gibt es etwas overhead. Vielleicht lässt man es aber auch. Könnte man überlegen das eleganter zu lösen.

**Comment by akohlbecker** [comment]
ich denke dass  ist jetzt durch die `AbstractFilterMethod` deutlich besser.

Wenn ja, könntest du @kasoft das ticket schließen

**Comment by kasoft** [comment]
Habe die getReplaceTokens jetzt etwas modifiziert, damit sie einfach einen array mit der korrekten datenstruktur zurückgibt. hier sind dann auch die verschachtelungen aufgelöst, welche zu einer andere datenstruktur geführt haben. mit dieser version ist es aber deutlich einfacher, mehr und neue filter zu machen  👍
